version: "3"
services:
  develop:
    build: .
    ports:
      - "4500:4500"
    container_name: graph-client
    env_file:
      - dev.env
    environment:
      PORT: 4500
      NODE_PATH: app/src
      CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      API_VERSION: v1
      # NEO4J_URI: bolt://mymachine:7687
      NEO4J_USER:
      NEO4J_PASSWORD:
      CT_REGISTER_MODE: auto
    command: develop
    volumes:
      - ./app:/opt/graph-client/app
    depends_on:
      - graph

  graph:
    image: neo4j:3.2-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    volumes:
      - $HOME/docker/data/graph-client:/data
